services:
  crappy-db:
    container_name: crappy-shop-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=crappy
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local